driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: amazonlinux
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN echo /etc/resolv.conf
      - RUN echo 'nameserver 8.8.8.8' > /etc/resolv.conf

- name: debian-7
  driver:
    image: dokken/debian-7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: centos-6
  driver:
    image: dokken/centos-6
    pid_one_command: /sbin/init

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-latest
  driver:
    image: dokken/fedora-latest
    pid_one_command: /usr/lib/systemd/systemd

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: opensuse-leap
  driver:
    image: dokken/opensuse-leap
    pid_one_command: /bin/systemd

suites:
- name: package
  run_list:
  - recipe[test::default]
- name: binary
  run_list:
  - recipe[test::binary]
- name: source
  run_list:
  - recipe[test::source]
  excludes:
    - centos-6
- name: npm
  run_list:
  - recipe[test::npm]
- name: npm_embedded
  run_list:
  - recipe[test::npm]
  attributes:
    nodejs:
      npm:
        install_method: embedded
- name: npm_source
  run_list:
  - recipe[test::npm]
  attributes:
    nodejs:
      npm:
        install_method: source
  excludes:
    - centos-6
- name: npm_packages
  run_list: recipe[nodejs]
  attributes:
    nodejs:
      npm_packages:
        - name: express
        - name: socket.io
          version: 1.0.4
        - name: express
          action: uninstall
